Repository blurry-x-face/getsetfoss, pull requests merged in 2019-11, with the labels that each got.

#13 Added myself as a participant
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#31 Added myself as participant
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#24 added myself as a participant
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#37 Adding myself as a participant
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#55 Added as Participant
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#70 add me as a participant
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#19 added myself as participants
  Data/participants.json
  assets/css/bootstrap.min.css
  assets/css/main.css
Labels: Very Easy, getsetfoss2019

#83 Mightymoin
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#67 Added myself as a participant
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#63 Add yourself as participant in participants.json
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#81 Add myself as participant
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#50 Update participants.json
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#45 added me as a participant
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#49 i am added as a participant
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#52 added myself to participants.json
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#115 Favicon added #114
  assets/img/get-set-foss.ico
  index.html
Labels: Easy, getsetfoss2019

#110 Mentors Section by nawab-shah
  assets/css/main.css
  assets/img/mentors/Pirate-Ship-Optical-Illusion.jpg
  index.html
Labels: Hard, getsetfoss2019

#117 Updated the points Criteria
  index.html
Labels: Very Easy, getsetfoss2019

#120 aligned Other sponsors to center issue #113
  index.html
Labels: Very Easy, getsetfoss2019

#116 leaderboard added
  Data/participants.json
  index.html
Labels: Very Easy, getsetfoss2019

#82 add myself as participant
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#96 Update participants.json
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#97 Add participant
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#99 Update participants.json
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#102 Added myself as participant issue#10
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#103 Added myself as participant issue#10
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#104 I have added myself as participant issue # 10
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#106 added myself as participants
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#109 Add me as a participant.
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#123 Update participate.json
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#125 Final Mentors section by nawab-shah
  Data/mentors.json
  assets/css/main.css
  assets/js/main.js
  index.html
Labels: getsetfoss2019

#126 Participants section
  Data/participants.json
  assets/css/main.css
  assets/js/main.js
  index.html
Labels: getsetfoss2019

#127 Update participants.json
  Data/participants.json
Labels: Very Easy, getsetfoss2019

#129 Update participants.json
  Data/participants.json
Labels: Very Easy, getsetfoss2019
